package me.exyin.partiesgui.clickevents.enums;

public enum ClickEventEnum {
  PARTY_CHANGE_COLOR,
  PARTY_CHANGE_DESC,
  PARTY_CHANGE_MOTD,
  PARTY_CHANGE_NAME,
  PARTY_CHANGE_TAG,
  PARTY_HOME,
  PARTY_INVITATIONS,
  PARTY_INVITE,
  PARTY_MEMBERS,
  PARTY_SETTINGS,
  GUI_PREVIOUS_PAGE,
  GUI_NEXT_PAGE,
  GUI_BACK,
  GUI_CLOSE,
  NOTHING
}
